Vagrant.configure(2) do |config|
  config.vm.box = "iknite/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" 

  config.vm.provision "shell", path: "install_svcSunSet.sh"
  config.vm.provision "shell", path: "install_initd.sh"
  config.vm.provision "shell", path: "start_svcSunSet.sh", privileged: true

end
