#! /bin/sh

### BEGIN INIT INFO
# Provides:		svcSunSetRise
# Required-Start:	
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Service to calculate sunrise and sunset
### END INIT INFO


python /var/www/html/svcSunRise/src/SunSetRise.py &>/var/log/svcSunRise/svcSunRise.log &
